# Generated by Django 4.0.2 on 2022-02-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
