# Generated by Django 4.0.2 on 2022-02-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blog_image_blog_usernam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='usernam',
            new_name='userna',
        ),
    ]
