# Generated by Django 4.0.2 on 2022-02-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_usernam_blog_userna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='userna',
            new_name='use',
        ),
    ]
