# Generated by Django 4.0.2 on 2022-02-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_userna_blog_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='use',
        ),
    ]
