# Generated by Django 4.0.2 on 2022-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_blog_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='static/'),
        ),
    ]
