# Generated by Django 4.0.2 on 2022-02-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_blog_date_alter_blog_desc_alter_blog_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
